USE ROLE ACCOUNTADMIN;
CREATE COMPUTE POOL IF NOT EXISTS APPS_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS      -- 2 vCPU / 8 GB: plenty for a dashboard
  AUTO_SUSPEND_SECS = 3600
  COMMENT = 'Compute pool for apps in the APPS layer';

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE NETWORK RULE PYPI_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('pypi.org', 'files.pythonhosted.org');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION PYPI_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (PYPI_NETWORK_RULE)
  ENABLED = TRUE
  COMMENT = 'Allows Streamlit apps to install packages from PyPI';

DROP ROLE SIRA_AI_APPS;
CREATE ROLE SIRA_AI_APPS_ADMIN;

GRANT USAGE ON DATABASE ARISDATA_CONVERSATIONAL_ANALYTICS TO ROLE SIRA_AI_APPS_ADMIN;
GRANT USAGE ON SCHEMA ARISDATA_CONVERSATIONAL_ANALYTICS.APPS TO ROLE SIRA_AI_APPS_ADMIN;
GRANT CREATE STREAMLIT ON SCHEMA ARISDATA_CONVERSATIONAL_ANALYTICS.APPS TO ROLE SIRA_AI_APPS_ADMIN;
GRANT USAGE, MONITOR ON COMPUTE POOL APPS_COMPUTE_POOL TO ROLE SIRA_AI_APPS_ADMIN;
GRANT USAGE ON INTEGRATION PYPI_ACCESS_INTEGRATION TO ROLE SIRA_AI_APPS_ADMIN;
GRANT USAGE ON WAREHOUSE SIRA_WH_ENGINEERING TO ROLE SIRA_AI_APPS_ADMIN;

GRANT ROLE SIRA_AI_APPS_ADMIN TO USER MAHAMFARRUKH;
GRANT ROLE SIRA_AI_APPS_ADMIN TO USER AKSHAY;

CREATE OR REPLACE API INTEGRATION CONVERSATIONAL_APP_GIT_INTEGRATION
    API_PROVIDER = GIT_HTTPS_API
    API_ALLOWED_PREFIXES = ('https://github.com/ArisData-ai/')
    ALLOWED_AUTHENTICATION_SECRETS = (ARISDATA_CONVERSATIONAL_ANALYTICS.APPS.CONVERSATIONAL_APP_GITHUB_PAT)
    ENABLED = TRUE
    COMMENT = 'Git integration for snowflake-conversational-app';
